name: npm-package-updater

on:
  push:
  schedule:
    - cron: '20 * * * *'
    - cron: '*/10 * * * *'

jobs:
  update-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up NodeJS 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Run version npm-package-updater
        run: npx npm-check-updates -t minor -u
        
      - name: configure git
        run: git config --global user.email "dep-update-bot@permafrost.dev" && git config --global user.name "Dependency Update Bot"

      - name: commit changes
        run: git checkout -b dep-updates && git add package.json && git commit -m'dependency updates' && git push origin dep-updates
        
      - name: Create pull request
        run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} gh pr create --head "main" --base "dep-updates" --title "[updates] npm dependency updates" --body "This PR updates minor versions for all npm dependencies."
        
#      - name: Commit changes
#        uses: stefanzweifel/git-auto-commit-action@v4
#        with:
#          commit_message: bump dependency versions
